name: chemml
channels:
    - conda-forge
dependencies:
    - python=3.6
    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi

#      # chemml depends
#    - openbabel
#    - rdkit

    - pip:
      - chemml
